"""kaos-agents — Agentic runtime with persistent memory for KAOS."""

from __future__ import annotations

from kaos_agents._version import __version__
from kaos_agents.agent import BaseAgent
from kaos_agents.config import Agent, AgentPattern
from kaos_agents.context import TriageResult, assemble_context, triage_corpus
from kaos_agents.delegation import (
    DelegatedAgent,
    DelegationDepthExceeded,
    agent_as_tool,
    current_delegation_depth,
)
from kaos_agents.errors import (
    EventDeserializationError,
    EventSerializationError,
    EvictionError,
    KaosAgentError,
    MemoryBudgetExceededError,
    SectionNotConfiguredError,
    SessionCorruptedError,
    SessionNotFoundError,
)
from kaos_agents.events import (
    CitationFound,
    EventEmitter,
    EvidenceInsufficient,
    GroundingRefusalTriggered,
    HandoffStart,
    IntentClassified,
    KaosEvent,
    LifecycleEvent,
    MemoryUpdated,
    PlanProposed,
    PlanStepSummary,
    RunError,
    StepComplete,
    StepStart,
    StreamDelta,
    SubagentComplete,
    SubagentStart,
    TextDelta,
    ThinkingDelta,
    ToolCallApprovalRequired,
    ToolCallArgsDelta,
    ToolCallResult,
    ToolCallStart,
    ToolCallSummary,
    TurnComplete,
    TurnStart,
    deserialize_event,
    serialize_event,
)
from kaos_agents.hooks import AuditHook, BaseHook, CostTrackingHook, HookAction, LoggingHook
from kaos_agents.interrupts import PendingToolCall, RunState
from kaos_agents.memory import (
    EvictionPolicy,
    MemoryItem,
    MemoryType,
    PersistenceMode,
    Section,
    SectionConfig,
    SessionMemory,
    SessionStore,
    SummarizationPolicy,
)
from kaos_agents.otel import OTelHook
from kaos_agents.permissions import PermissionPolicy
from kaos_agents.planning import (
    ComposeResult,
    Decision,
    EvalMode,
    Judgment,
    PlanBudget,
    PlanGraph,
    PrimitiveTrace,
    RouteResult,
    Step,
    StepStatus,
    StepType,
    StopReason,
)
from kaos_agents.runner import Runner
from kaos_agents.settings import KaosAgentSettings
from kaos_agents.tools import register_agent_tools
from kaos_agents.types import (
    AgentResponse,
    IntentResult,
    IntentType,
    PermissionDecision,
    PermissionRule,
    ToolCallRecord,
)
from kaos_agents.types.providers import BALANCED, FAST, STRONG, ModelRole, ProviderConfig
from kaos_agents.wire import events_to_jsonl, events_to_sse

__all__ = [
    "BALANCED",
    "FAST",
    "STRONG",
    "Agent",
    "AgentPattern",
    "AgentResponse",
    "AuditHook",
    "BaseAgent",
    "BaseHook",
    "CitationFound",
    "ComposeResult",
    "CostTrackingHook",
    "Decision",
    "DelegatedAgent",
    "DelegationDepthExceeded",
    "EvalMode",
    "EventDeserializationError",
    "EventEmitter",
    "EventSerializationError",
    "EvictionError",
    "EvictionPolicy",
    "EvidenceInsufficient",
    "GroundingRefusalTriggered",
    "HandoffStart",
    "HookAction",
    "IntentClassified",
    "IntentResult",
    "IntentType",
    "Judgment",
    "KaosAgentError",
    "KaosAgentSettings",
    "KaosEvent",
    "LifecycleEvent",
    "LoggingHook",
    "MemoryBudgetExceededError",
    "MemoryItem",
    "MemoryType",
    "MemoryUpdated",
    "ModelRole",
    "OTelHook",
    "PendingToolCall",
    "PermissionDecision",
    "PermissionPolicy",
    "PermissionRule",
    "PersistenceMode",
    "PlanBudget",
    "PlanGraph",
    "PlanProposed",
    "PlanStepSummary",
    "PrimitiveTrace",
    "ProviderConfig",
    "RouteResult",
    "RunError",
    "RunState",
    "Runner",
    "Section",
    "SectionConfig",
    "SectionNotConfiguredError",
    "SessionCorruptedError",
    "SessionMemory",
    "SessionNotFoundError",
    "SessionStore",
    "Step",
    "StepComplete",
    "StepStart",
    "StepStatus",
    "StepType",
    "StopReason",
    "StreamDelta",
    "SubagentComplete",
    "SubagentStart",
    "SummarizationPolicy",
    "TextDelta",
    "ThinkingDelta",
    "ToolCallApprovalRequired",
    "ToolCallArgsDelta",
    "ToolCallRecord",
    "ToolCallResult",
    "ToolCallStart",
    "ToolCallSummary",
    "TriageResult",
    "TurnComplete",
    "TurnStart",
    "__version__",
    "agent_as_tool",
    "assemble_context",
    "current_delegation_depth",
    "deserialize_event",
    "events_to_jsonl",
    "events_to_sse",
    "register_agent_tools",
    "serialize_event",
    "triage_corpus",
]
