"""kaos-agents — Agentic runtime with persistent memory for KAOS."""

from __future__ import annotations

from kaos_agents._version import __version__
from kaos_agents.base import KaosAgent, KaosPattern
from kaos_agents.config import Agent, AgentPattern
from kaos_agents.context import (
    TriageResult,
    assemble_context,
    expand_with_graph,
    triage_corpus,
)
from kaos_agents.decorators import FunctionHook, hook
from kaos_agents.errors import (
    EventDeserializationError,
    EventSerializationError,
    EvictionError,
    KaosAgentError,
    MemoryBudgetExceededError,
    SectionNotConfiguredError,
    SessionCorruptedError,
    SessionNotFoundError,
)
from kaos_agents.events import (
    BudgetExceeded,
    CitationFound,
    EventEmitter,
    EvidenceInsufficient,
    GroundingRefusalTriggered,
    IntentClassified,
    KaosEvent,
    LifecycleEvent,
    MemoryEvent,
    MemoryEventKind,
    PlanProposed,
    PlanStepSummary,
    RunError,
    Span,
    SpanPhase,
    SpanSubject,
    StreamDelta,
    TextDelta,
    ThinkingDelta,
    ToolCallApprovalRequired,
    ToolCallArgsDelta,
    ToolCallSummary,
    TurnSummary,
    deserialize_event,
    deserialize_event_json,
    serialize_event,
    serialize_event_json,
)
from kaos_agents.hooks import (
    AuditHook,
    CostTrackingHook,
    HookAction,
    KaosHook,
    LoggingHook,
    dispatch_hook,
)
from kaos_agents.hooks.otel import OTelHook
from kaos_agents.memory import (
    EvictionPolicy,
    MemoryItem,
    MemoryType,
    PersistenceMode,
    Section,
    SectionConfig,
    SessionMemory,
    SessionStore,
    SummarizationPolicy,
    agent_iri,
    doc_iri,
    emit_from_event,
    finding_iri,
    step_iri,
    tool_call_iri,
)
from kaos_agents.patterns import ChatAgent, PlanExecuteAgent, ResearchAgent
from kaos_agents.planning import (
    ComposeResult,
    Decision,
    EvalMode,
    Judgment,
    PlanBudget,
    PlanGraph,
    PrimitiveTrace,
    RouteResult,
    Step,
    StepStatus,
    StepType,
    StopReason,
)
from kaos_agents.registry import (
    AgentToolSpecRegistry,
    EventRegistry,
    HookRegistry,
    PatternRegistry,
    ToolDataTypeRegistry,
    ToolGroupRegistry,
    default_event_registry,
    default_hook_registry,
    default_pattern_registry,
    default_tool_data_type_registry,
    default_tool_group_registry,
    default_tool_spec_registry,
)
from kaos_agents.runtime.agent import BaseAgent
from kaos_agents.runtime.delegation import (
    DelegatedAgent,
    DelegationDepthExceeded,
    agent_as_tool,
    current_delegation_depth,
)
from kaos_agents.runtime.interrupts import PendingToolCall, RunState
from kaos_agents.runtime.permissions import PermissionPolicy
from kaos_agents.runtime.runner import Runner
from kaos_agents.settings import KaosAgentSettings
from kaos_agents.tools import register_agent_tools
from kaos_agents.types import (
    AgentMetadata,
    AgentResponse,
    AgentToolRegistration,
    AgentToolSpec,
    DataType,
    EventMetadata,
    HookMetadata,
    IntentResult,
    IntentType,
    PatternMetadata,
    PermissionDecision,
    PermissionRule,
    RecipeMetadata,
    ToolCallRecord,
    ToolDataTypeSpec,
    ToolExecution,
    ToolGroup,
)
from kaos_agents.types.providers import BALANCED, FAST, STRONG, ModelRole, ProviderConfig
from kaos_agents.wire import events_to_jsonl, events_to_sse

__all__ = [
    "BALANCED",
    "FAST",
    "STRONG",
    "Agent",
    "AgentMetadata",
    "AgentPattern",
    "AgentResponse",
    "AgentToolRegistration",
    "AgentToolSpec",
    "AgentToolSpecRegistry",
    "AuditHook",
    "BaseAgent",
    "BudgetExceeded",
    "ChatAgent",
    "CitationFound",
    "ComposeResult",
    "CostTrackingHook",
    "DataType",
    "Decision",
    "DelegatedAgent",
    "DelegationDepthExceeded",
    "EvalMode",
    "EventDeserializationError",
    "EventEmitter",
    "EventMetadata",
    "EventRegistry",
    "EventSerializationError",
    "EvictionError",
    "EvictionPolicy",
    "EvidenceInsufficient",
    "FunctionHook",
    "GroundingRefusalTriggered",
    "HookAction",
    "HookMetadata",
    "HookRegistry",
    "IntentClassified",
    "IntentResult",
    "IntentType",
    "Judgment",
    "KaosAgent",
    "KaosAgentError",
    "KaosAgentSettings",
    "KaosEvent",
    "KaosHook",
    "KaosPattern",
    "LifecycleEvent",
    "LoggingHook",
    "MemoryBudgetExceededError",
    "MemoryEvent",
    "MemoryEventKind",
    "MemoryItem",
    "MemoryType",
    "ModelRole",
    "OTelHook",
    "PatternMetadata",
    "PatternRegistry",
    "PendingToolCall",
    "PermissionDecision",
    "PermissionPolicy",
    "PermissionRule",
    "PersistenceMode",
    "PlanBudget",
    "PlanExecuteAgent",
    "PlanGraph",
    "PlanProposed",
    "PlanStepSummary",
    "PrimitiveTrace",
    "ProviderConfig",
    "RecipeMetadata",
    "ResearchAgent",
    "RouteResult",
    "RunError",
    "RunState",
    "Runner",
    "Section",
    "SectionConfig",
    "SectionNotConfiguredError",
    "SessionCorruptedError",
    "SessionMemory",
    "SessionNotFoundError",
    "SessionStore",
    "Span",
    "SpanPhase",
    "SpanSubject",
    "Step",
    "StepStatus",
    "StepType",
    "StopReason",
    "StreamDelta",
    "SummarizationPolicy",
    "TextDelta",
    "ThinkingDelta",
    "ToolCallApprovalRequired",
    "ToolCallArgsDelta",
    "ToolCallRecord",
    "ToolCallSummary",
    "ToolDataTypeRegistry",
    "ToolDataTypeSpec",
    "ToolExecution",
    "ToolGroup",
    "ToolGroupRegistry",
    "TriageResult",
    "TurnSummary",
    "__version__",
    "agent_as_tool",
    "agent_iri",
    "assemble_context",
    "current_delegation_depth",
    "default_event_registry",
    "default_hook_registry",
    "default_pattern_registry",
    "default_tool_data_type_registry",
    "default_tool_group_registry",
    "default_tool_spec_registry",
    "deserialize_event",
    "deserialize_event_json",
    "dispatch_hook",
    "doc_iri",
    "emit_from_event",
    "events_to_jsonl",
    "events_to_sse",
    "expand_with_graph",
    "finding_iri",
    "hook",
    "register_agent_tools",
    "serialize_event",
    "serialize_event_json",
    "step_iri",
    "tool_call_iri",
    "triage_corpus",
]
